config/routes.rb
Rails.application.routes.draw do
  root 'inquiries#new'
  
  post 'inquiries/confirm'
  post 'inquiries/thanks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true, length: { in: 1..20 }
  validates :email, presence: true
  validates :content, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new 
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      render "confirm"
    else
      render action: :new
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver_now
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :relationship, :content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/confirm.html.erb
<div class="confirmPage">
  <div class='container'>
    <h1 class="confirmPage_title">伝えたい内容</h1>
    <%= form_with model: @inquiry, url: inquiries_thanks_path, method: :post, local: true do |f| %>
      <div class="confirmForm_item">
        <h3>感謝を伝えたい人のお名前</h3>
        <div>
          <%= f.hidden_field :name %>
          <%= @inquiry.name %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>感謝を伝えたい人のメールアドレス</h3>
        <div>
          <%= f.hidden_field :email %>
          <%= @inquiry.email %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>感謝を伝えたい人との関係</h3>
        <div>
          <%= f.hidden_field :relationship %>
          <%= @inquiry.relationship %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>日頃からの感謝のキモチ</h3>
        <div>
          <% if @inquiry.content.empty? %>
           特になし
          <% else %>
           <%= @inquiry.content %>
          <% end%>
          <%= f.hidden_field :content %>
        </div>
      </div>
      <div class="text-center">
        <%= link_to "入力画面に戻る", root_path, class: "btn btn-info"%>
        <%= f.submit '送信する', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/inquiries/new.html.erb
<div class='topPage'>
  <div class="container">
    <h1>『感謝のキモチ』通知代理サービス</h1>
    <p>身近にいる人へ感謝のキモチを「伝えたい！！」けど照れくさい・時間がない。そんな方の代理をいたします。
    </p>
    
    <%= form_with model: @inquiry, url: { action: :confirm }, html: { class: 'form' }, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
       <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "お名前" %>
      </div>
      <div class="form-group">
       <%= f.label :email %>
        <%= f.text_field :email, autofocus: true, class: "form-control", placeholder: "メールアドレス" %>
      </div>
      <div class="form-group">
        <%= f.label :relationship %>
        <%= f.select(:relationship, [["親", "親"], ["夫婦", "夫婦"], ["恋人", "恋人"], ["友人", "友人"], ["上司", "上司"], ["先輩", "先輩"]], {}, class: "form-control") %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control", placeholder: "伝えたいことを入力してください" %>
      </div>
       <div class="text-center"><%= f.submit '確認画面へ', class: 'btn btn-primary' %></div>
    <% end %>
  </div>
</div>

app/views/inquiries/thanks.html.erb
<div class='thanksPage'>
  <div class='container'>
    <p class="thanksPage_message">ご利用ありがとうございました！</p>
    <div class="text-center"><%= link_to "トップへ戻る", root_path, class: "btn btn-primary" %></div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TsuTaERu</title>
    <%# viewport導入 %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>